# Postgres Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
---
# Server Secret
apiVersion: v1
kind: Secret
metadata:
  name: server-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/docker_test_db?schema=public"