
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-temp.yaml
- k8s/service.yaml
- k8s/ingress.yaml
namespace: hello-gitops
commonLabels:
  color: blue
images:
- name: hello-gitops
  newName: us-central1-docker.pkg.dev/mindful-phalanx-472718-e8/homework-4/hello-gitops
  newTag: 359af8f81e51459b98d685845ef4ec3a16365bba
