[tool.poetry]
name = "advanced-task"
version = "0.1.0"
description = ""
authors = ["Serhii Sliadniev <s.sliadniev@qyantumobile.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.51.0"
openai = "^2.7.1"
